# Generated by Django 4.1.5 on 2023-01-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='univercity',
            new_name='university',
        ),
    ]
