# Generated by Django 4.1.5 on 2023-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_rename_univercity_profile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
